apiVersion: v1
items:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: rmqdemo-config
      namespace: default
    data:
      entrypoint.sh: |
        #!/bin/bash
        set -e
        # Start RMQ from entry point.
        # This will ensure that environment variables passed
        # will be honored
        /usr/local/bin/docker-entrypoint.sh rabbitmq-server -detached
        # Do the cluster dance
        rabbitmqctl stop_app
        # MUST have this line, otherwise the node will be blocked to join cluster again.
        rabbitmqctl reset
        rabbitmqctl join_cluster --ram rabbit@rabbitmq1
        # Stop the entire RMQ server. This is done so that we
        # can attach to it again, but without the -detached flag
        # making it run in the forground
        rabbitmqctl stop
        # Wait a while for the app to really stop
        sleep 2s
        # Start it
        rabbitmq-server
      rabbitmq.conf: |
        loopback_users.guest = false
        listeners.tcp.default = 5672
        management.listeners.port = 15672
        management.listeners.ssl = false
        cluster_partition_handling = autoheal
      haproxy.cfg: |
        global
            log     127.0.0.1  local0 debug
            log     127.0.0.1  local1 notice
            daemon
            maxconn 4096

        defaults
            log     global
            mode    tcp
            option  tcplog
            option  dontlognull
            option  redispatch
            retries 3
            option  abortonclose
            maxconn 4096
            timeout connect  5000ms
            timeout client  10000ms
            timeout server  10000ms

        listen private_monitoring
            bind    0.0.0.0:8100
            mode    http
            stats   refresh  5s
            stats   uri  /stats
            stats   realm   Haproxy
            stats   auth  admin:admin

        listen rabbitmq_cluster
            bind    0.0.0.0:5672
            mode    tcp
            option  tcplog
            balance roundrobin
            server  rabbitmq1  rabbitmq1:5672  check  inter  5000  rise  2  fall  3
            server  rabbitmq2  rabbitmq2:5672  check  inter  5000  rise  2  fall  3
            server  rabbitmq3  rabbitmq3:5672  check  inter  5000  rise  2  fall  3

        listen rabbitmq_admin
            bind    0.0.0.0:15672
            mode    http
            server  rabbitmq1 rabbitmq1:15672
            # server  rabbitmq2 rabbitmq2:15672
            # server  rabbitmq3 rabbitmq3:15672
kind: List
metadata: {}
