apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        io.kompose.service: haproxy
      name: haproxy
    spec:
      ports:
        - name: "8100"
          port: 8100
          targetPort: 8100
        - name: "5672"
          port: 5672
          targetPort: 5672
        - name: "15672"
          port: 15672
          targetPort: 15672
      selector:
        io.kompose.service: haproxy
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      labels:
        io.kompose.service: consumer
      name: consumer
    spec:
      replicas: 1
      strategy: {}
      template:
        metadata:
          labels:
            io.kompose.service: consumer
        spec:
          containers:
            - image: 192.168.0.35/rmqdemo/consumer:0.1
              name: consumer
              resources:
                limits:
                  cpu: 100m
                  memory: 200Mi
                requests:
                  cpu: 100m
                  memory: 200Mi
          restartPolicy: Always
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      labels:
        io.kompose.service: haproxy
      name: haproxy
    spec:
      replicas: 1
      strategy: {}
      template:
        metadata:
          labels:
            io.kompose.service: haproxy
        spec:
          containers:
            - image: haproxy:alpine
              name: haproxy
              ports:
                - containerPort: 8100
                - containerPort: 5672
                - containerPort: 15672
              resources:
                limits:
                  cpu: 100m
                  memory: 200Mi
                requests:
                  cpu: 100m
                  memory: 200Mi
          hostname: haproxy
          restartPolicy: Always
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      labels:
        io.kompose.service: producer
      name: producer
    spec:
      replicas: 1
      strategy: {}
      template:
        metadata:
          labels:
            io.kompose.service: producer
        spec:
          containers:
            - env:
                - name: PRODUCER_DELAY
                  value: "0.001"
              image: 192.168.0.35/rmqdemo/producer:0.1
              name: producer
              resources:
                limits:
                  cpu: 100m
                  memory: 200Mi
                requests:
                  cpu: 100m
                  memory: 200Mi
          restartPolicy: Always
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      labels:
        io.kompose.service: rabbitmq1
      name: rabbitmq1
    spec:
      replicas: 1
      strategy: {}
      template:
        metadata:
          labels:
            io.kompose.service: rabbitmq1
        spec:
          containers:
            - env:
                - name: RABBITMQ_ERLANG_COOKIE
                  value: "123456"
              image: rabbitmq:3.7-management
              livenessProbe:
                exec:
                  command:
                    - rabbitmq-diagnostics
                    - ping
                    - -t
                    - "10"
              name: rabbitmq1
              resources:
                limits:
                  cpu: 100m
                  memory: 200Mi
                requests:
                  cpu: 100m
                  memory: 200Mi
          hostname: rabbitmq1
          restartPolicy: Always
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      labels:
        io.kompose.service: rabbitmq2
      name: rabbitmq2
    spec:
      replicas: 1
      strategy: {}
      template:
        metadata:
          creationTimestamp: null
          labels:
            io.kompose.service: rabbitmq2
        spec:
          containers:
            - command:
                - /usr/local/bin/entrypoint.sh
              env:
                - name: RABBITMQ_ERLANG_COOKIE
                  value: "123456"
              image: rabbitmq:3.7-management
              livenessProbe:
                exec:
                  command:
                    - rabbitmq-diagnostics
                    - ping
                    - -t
                    - "10"
              name: rabbitmq2
              resources:
                limits:
                  cpu: 100m
                  memory: 200Mi
                requests:
                  cpu: 100m
                  memory: 200Mi
          hostname: rabbitmq2
          restartPolicy: Always
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      labels:
        io.kompose.service: rabbitmq3
      name: rabbitmq3
    spec:
      replicas: 1
      strategy: {}
      template:
        metadata:
          labels:
            io.kompose.service: rabbitmq3
        spec:
          containers:
            - command:
                - /usr/local/bin/entrypoint.sh
              env:
                - name: RABBITMQ_ERLANG_COOKIE
                  value: "123456"
              image: 192.168.0.35/rmqdemo/3.7-management
              livenessProbe:
                exec:
                  command:
                    - rabbitmq-diagnostics
                    - ping
                    - -t
                    - "10"
              name: rabbitmq3
              resources:
                limits:
                  cpu: 100m
                  memory: 200Mi
                requests:
                  cpu: 100m
                  memory: 200Mi
          hostname: rabbitmq3
          restartPolicy: Always
kind: List
metadata: {}
