apiVersion: v1
items:
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      labels:
        dce.daocloud.io/app: rabbitmq-demo
        dce.daocloud.io/component: consumer
      name: consumer
    spec:
      replicas: 1
      strategy: {}
      template:
        metadata:
          labels:
            dce.daocloud.io/app: rabbitmq-demo
            dce.daocloud.io/component: consumer
        spec:
          containers:
            - image: 192.168.0.35/rmqdemo/consumer:0.1
              name: consumer
              resources:
                limits:
                  cpu: 100m
                  memory: 200Mi
                requests:
                  cpu: 100m
                  memory: 200Mi
          restartPolicy: Always
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      labels:
        dce.daocloud.io/app: rabbitmq-demo
        dce.daocloud.io/component: haproxy
      name: haproxy
    spec:
      replicas: 1
      strategy: {}
      template:
        metadata:
          labels:
            dce.daocloud.io/app: rabbitmq-demo
            dce.daocloud.io/component: haproxy
        spec:
          containers:
            - image: haproxy:alpine
              name: haproxy
              ports:
                - containerPort: 8100
                - containerPort: 5672
                - containerPort: 15672
              resources:
                limits:
                  cpu: 100m
                  memory: 200Mi
                requests:
                  cpu: 100m
                  memory: 200Mi
              volumeMounts:
              - name: haproxy-config
                mountPath: /usr/local/etc/haproxy/
          volumes:
            - name: haproxy-config
              configMap:
                name: rmqdemo-config
                items:
                - key: haproxy.cfg
                  path: haproxy.cfg
          hostname: haproxy
          restartPolicy: Always
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      labels:
        dce.daocloud.io/app: rabbitmq-demo
        dce.daocloud.io/component: producer
      name: producer
    spec:
      replicas: 1
      strategy: {}
      template:
        metadata:
          labels:
            dce.daocloud.io/app: rabbitmq-demo
            dce.daocloud.io/component: producer
        spec:
          containers:
            - env:
                - name: PRODUCER_DELAY
                  value: "0.001"
              image: 192.168.0.35/rmqdemo/producer:0.1
              name: producer
              resources:
                limits:
                  cpu: 100m
                  memory: 200Mi
                requests:
                  cpu: 100m
                  memory: 200Mi
          restartPolicy: Always
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      labels:
        dce.daocloud.io/app: rabbitmq-demo
        dce.daocloud.io/component: rabbitmq1
      name: rabbitmq1
    spec:
      replicas: 1
      strategy: {}
      template:
        metadata:
          labels:
            dce.daocloud.io/app: rabbitmq-demo
            dce.daocloud.io/component: rabbitmq1
        spec:
          containers:
            - env:
                - name: RABBITMQ_ERLANG_COOKIE
                  value: "123456"
              image: 192.168.0.35/rmqdemo/rabbitmq:3.7-management
              livenessProbe:
                exec:
                  command:
                    - rabbitmq-diagnostics
                    - ping
                    - -t
                    - "10"
              name: rabbitmq1
              resources:
                limits:
                  cpu: 100m
                  memory: 200Mi
                requests:
                  cpu: 100m
                  memory: 200Mi
              volumeMounts:
              - name: rmq1-config
                mountPath: /etc/rabbitmq/
          volumes:
            - name: rmq1-config
              configMap:
                name: rmqdemo-config
                defaultMode: 511
                items:
                - key: rabbitmq.conf
                  path: rabbitmq.conf
          hostname: rabbitmq1
          restartPolicy: Always
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      labels:
        dce.daocloud.io/app: rabbitmq-demo
        dce.daocloud.io/component: rabbitmq2
      name: rabbitmq2
    spec:
      replicas: 1
      strategy: {}
      template:
        metadata:
          creationTimestamp: null
          labels:
            dce.daocloud.io/app: rabbitmq-demo
            dce.daocloud.io/component: rabbitmq2
        spec:
          containers:
            - command:
                - /usr/local/bin/docker-entrypoint.sh
              env:
                - name: RABBITMQ_ERLANG_COOKIE
                  value: "123456"
              image: 192.168.0.35/rmqdemo/rabbitmq:3.7-management
              livenessProbe:
                exec:
                  command:
                    - rabbitmq-diagnostics
                    - ping
                    - -t
                    - "10"
              name: rabbitmq2
              resources:
                limits:
                  cpu: 100m
                  memory: 200Mi
                requests:
                  cpu: 100m
                  memory: 200Mi
              volumeMounts:
              - name: rmq2-config
                mountPath: /etc/rabbitmq/
              - name: rmq2-entrypoint
                mountPath: /usr/local/bin/
          volumes:
            - name: rmq2-config
              configMap:
                name: rmqdemo-config
                defaultMode: 511
                items:
                - key: rabbitmq.conf
                  path: rabbitmq.conf
            - name: rmq2-entrypoint
              configMap:
                name: rmqdemo-config
                defaultMode: 511
                items:
                - key: entrypoint.sh
                  path: docker-entrypoint.sh
          hostname: rabbitmq2
          restartPolicy: Always
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      labels:
        dce.daocloud.io/app: rabbitmq-demo
        dce.daocloud.io/component: rabbitmq3
      name: rabbitmq3
    spec:
      replicas: 1
      strategy: {}
      template:
        metadata:
          labels:
            dce.daocloud.io/app: rabbitmq-demo
            dce.daocloud.io/component: rabbitmq3
        spec:
          containers:
            - command:
                - /usr/local/bin/docker-entrypoint.sh
              env:
                - name: RABBITMQ_ERLANG_COOKIE
                  value: "123456"
              image: 192.168.0.35/rmqdemo/rabbitmq:3.7-management
              livenessProbe:
                exec:
                  command:
                    - rabbitmq-diagnostics
                    - ping
                    - -t
                    - "10"
              name: rabbitmq3
              resources:
                limits:
                  cpu: 100m
                  memory: 200Mi
                requests:
                  cpu: 100m
                  memory: 200Mi
              volumeMounts:
              - name: rmq3-config
                mountPath: /etc/rabbitmq/
              - name: rmq3-entrypoint
                mountPath: /usr/local/bin/
          volumes:
            - name: rmq3-config
              configMap:
                name: rmqdemo-config
                defaultMode: 511
                items:
                - key: rabbitmq.conf
                  path: rabbitmq.conf
            - name: rmq3-entrypoint
              configMap:
                name: rmqdemo-config
                defaultMode: 511
                items:
                - key: entrypoint.sh
                  path: docker-entrypoint.sh
          hostname: rabbitmq3
          restartPolicy: Always
kind: List
metadata: {}
